name: Run Selenium Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-rerunfailures

    - name: Run tests and generate report
      run: |
        mkdir -p reports screenshots
        pytest tests/ --html=reports/report.html --self-contained-html --reruns 2 --reruns-delay 2

    - name: Upload HTML report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: html-report
        path: reports/report.html

    - name: Upload Screenshots
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: screenshots
        path: screenshots/
